/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import primeanalyzer.model.Person;

import static org.junit.Assert.*;

public class PersonTest {
    @Test public void testSomeLibraryMethod() {
        Person classUnderTest = new Person("Mr. Gepetto");
        assertTrue("Assert Name retrieved correctly", classUnderTest.getName().equals("Mr. Gepetto"));
        assertTrue("Assert Id retrieved correctly", classUnderTest.getId() == 0);
    }
}
